# Generated by Django 4.2.5 on 2023-09-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('inn', models.CharField(max_length=12, verbose_name='ИНН')),
                ('age', models.IntegerField(default=None, verbose_name='Возраст')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Create date')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Change date')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='Delete date')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
            ],
        ),
    ]
